### ISSUE TITLE
problem with cryptograph-version installed by ansible core.

### ISSUE THREAD

**Issue by viktklass** [ansible-collections/community.crypto#305]
##### SUMMARY

the latest Cryptograph-version seems to give us issues when we're fetching a certification.
community.crypto.get_certificate:

```
- name: Get a cert from an https port
  community.crypto.get_certificate:
    host: "{{ inventory_hostname }}.example.com"
    port: 443
  delegate_to: localhost
  register: cert
```

this task fail with the following error:

```
fatal: [sw-nxos-lab-dh12-1b -> localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}
MSG:
MODULE FAILURE
See stdout/stderr for the exact error
MODULE_STDERR:
Traceback (most recent call last):
  File "/data/prodprog/netadmin/.ansible/tmp/ansible-tmp-1633935929.3941948-3551940-11751159509196/AnsiballZ_get_certificate.py", line 100, in <module>
    _ansiballz_main()
  File "/data/prodprog/netadmin/.ansible/tmp/ansible-tmp-1633935929.3941948-3551940-11751159509196/AnsiballZ_get_certificate.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/data/prodprog/netadmin/.ansible/tmp/ansible-tmp-1633935929.3941948-3551940-11751159509196/AnsiballZ_get_certificate.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.crypto.get_certificate_payload_3cq_8emt/ansible_community.crypto.get_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/get_certificate.py", line 388, in <module>
  File "/tmp/ansible_community.crypto.get_certificate_payload_3cq_8emt/ansible_community.crypto.get_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/get_certificate.py", line 358, in main
  File "/tmp/ansible_community.crypto.get_certificate_payload_3cq_8emt/ansible_community.crypto.get_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/cryptography_support.py", line 62, in cryptography_get_extensions_from_cert
AttributeError: 'builtins.Certificate' object has no attribute '_backend'
<localhost> EXEC /bin/bash -c 'rm -f -r /data/prodprog/netadmin/.ansible/tmp/ansible-tmp-1633935929.378052-3551939-242866785358026/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/data/prodprog/netadmin/.ansible/tmp/ansible-tmp-1633935929.378052-3551939-242866785358026/AnsiballZ_get_certificate.py", line 100, in <module>
    _ansiballz_main()
  File "/data/prodprog/netadmin/.ansible/tmp/ansible-tmp-1633935929.378052-3551939-242866785358026/AnsiballZ_get_certificate.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/data/prodprog/netadmin/.ansible/tmp/ansible-tmp-1633935929.378052-3551939-242866785358026/AnsiballZ_get_certificate.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.crypto.get_certificate_payload_mne7aclg/ansible_community.crypto.get_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/get_certificate.py", line 388, in <module>
  File "/tmp/ansible_community.crypto.get_certificate_payload_mne7aclg/ansible_community.crypto.get_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/get_certificate.py", line 358, in main
  File "/tmp/ansible_community.crypto.get_certificate_payload_mne7aclg/ansible_community.crypto.get_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/cryptography_support.py", line 62, in cryptography_get_extensions_from_cert
AttributeError: 'builtins.Certificate' object has no attribute '_backend'
```

We've made an workaround by reinstalling an older version of cryptography.
pip uninstall cryptography
pip install cryptography==3.4.8

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.crypto.get_certificate:

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.5] 
  config file = /tmp/builds/czU_fi8o/0/tfo-nat/ansible-dc2021/ansible.cfg
  configured module search path = ['/data/prodprog/netadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/builds/czU_fi8o/0/tfo-nat/ansible-dc2021/venv/lib64/python3.6/site-packages/ansible
  ansible collection location = /tmp/builds/czU_fi8o/0/tfo-nat/ansible-dc2021/collections
  executable location = /tmp/builds/czU_fi8o/0/tfo-nat/ansible-dc2021/venv/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
community.crypto 1.9.3  
```

##### CONFIGURATION

```paste below
venv/lib/python3.6/site-packages/ansible_collections
Collection       Version
---------------- -------
community.crypto 1.9.3  
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by felixfontein** [comment]
This has been fixed by cryptography 1.9.5, released 5 days ago (see #293 for the issue). It will be contained in the next Ansible 4 release, but you can install it manually if you need it now.

**Comment by profhase** [comment]
@felixfontein 
Would not be it a solution for upcoming issues of that kind to pin the cryptography version with requirements?

https://github.com/ansible/ansible/blob/devel/requirements.txt#L8

**Comment by elisdg** [comment]
we need to use ansilbe 4.5.0 in our environment. Unfortunately, installing "35.0.0" or "36.0.0" did not work and I also had to downgrade to 3.4.8 to fix it.
