### ISSUE TITLE
Getting error when trying to create openssl private key

### ISSUE THREAD

**Issue by zalent** [ansible-collections/community.crypto#415]
##### SUMMARY
getting error when trying to create openssl private key.  The file ansible_collections/community/crypto/plugins/module_utils/crypto/__init__.py is generated (no such file in github) and it has invalid import HAS_PYOPENSSL

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_privatekey

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/zalent/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zalent/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/zalent/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/zalent/.local/bin/ansible
  python version = 3.9.7 (default, Sep 21 2021, 00:13:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```paste below
Collection       Version
---------------- -------
community.crypto 2.2.2  
```

##### OS / ENVIRONMENT
CentOS 8 Stream
Python 3.9
pip 20.2.4

##### STEPS TO REPRODUCE
```yaml
  openssl_privatekey:
    path: "/tmp/ca.key"
    mode: "0600"
```

##### EXPECTED RESULTS
Private key is created

##### ACTUAL RESULTS
Import error occurred.
``` bash
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'HAS_PYOPENSSL'
fatal: [10.100.31.58]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.100.31.58 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1646215174.2740245-12877-147044420859366/AnsiballZ_openssl_privatekey.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1646215174.2740245-12877-147044420859366/AnsiballZ_openssl_privatekey.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1646215174.2740245-12877-147044420859366/AnsiballZ_openssl_privatekey.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_openssl_privatekey_payload_w_kss5md/ansible_openssl_privatekey_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_privatekey.py\", line 153, in <module>\r\n  File \"/tmp/ansible_openssl_privatekey_payload_w_kss5md/ansible_openssl_privatekey_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/__init__.py\", line 27, in <module>\r\nImportError: cannot import name 'HAS_PYOPENSSL'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by felixfontein** [comment]
Readable version of the stack trace:
```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1646215174.2740245-12877-147044420859366/AnsiballZ_openssl_privatekey.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1646215174.2740245-12877-147044420859366/AnsiballZ_openssl_privatekey.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1646215174.2740245-12877-147044420859366/AnsiballZ_openssl_privatekey.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_openssl_privatekey_payload_w_kss5md/ansible_openssl_privatekey_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_privatekey.py", line 153, in <module>
  File "/tmp/ansible_openssl_privatekey_payload_w_kss5md/ansible_openssl_privatekey_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/__init__.py", line 27, in <module>
ImportError: cannot import name 'HAS_PYOPENSSL'
```

**Comment by felixfontein** [comment]
Are you sure you are running this with the module from community.crypto 2.2.2? From the stack trace, it looks like you are running code from the stable-1 branch (https://github.com/ansible-collections/community.crypto/blob/stable-1/plugins/module_utils/crypto/__init__.py#L27), i.e. from an 1.x.y version of community.crypto.

Can you run ansible with `-vvvvv`? Then ansible-core will tell you which module file it used, and which module_utils it used on your local machine.

**Comment by zalent** [comment]
Edited environment info. aded pip 20.2.4 
So i have installed globally ansible 5.4.0 for my user via pip 20.2.4. Here is module utils directory, changelog rst, and __init__.py:
```
[zalent@*********** dev-machine]$ head /home/zalent/.local/lib/python3.9/site-packages/ansible_collections/community/crypto/CHANGELOG.rst 
==============================
Community Crypto Release Notes
==============================

.. contents:: Topics


v2.2.2
======

[zalent@*********** dev-machine]$ ls /home/zalent/.local/lib/python3.9/site-packages/ansible_collections/community/crypto/plugins/module_utils/crypto/
_asn1.py  cryptography_crl.py      __init__.py  module_backends  _objects_data.py  openssh.py  __pycache__           support.py
basic.py  cryptography_support.py  math.py      _obj2txt.py      _objects.py       pem.py      pyopenssl_support.py
[zalent@*********** dev-machine]$ cat /home/zalent/.local/lib/python3.9/site-packages/ansible_collections/community/crypto/plugins/module_utils/crypto/__init__.py 
# -*- coding: utf-8 -*-
#
# (c) 2016, Yanis Guenane <yanis+ansible@guenane.org>
#
# Ansible is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import, division, print_function
__metaclass__ = type


# THIS FILE IS FOR COMPATIBILITY ONLY! YOU SHALL NOT IMPORT IT!
#
# This fill will be removed eventually, so if you're using it,
# please stop doing so.

from .basic import (
    HAS_PYOPENSSL,
    CRYPTOGRAPHY_HAS_X25519,
    CRYPTOGRAPHY_HAS_X25519_FULL,
    CRYPTOGRAPHY_HAS_X448,
    CRYPTOGRAPHY_HAS_ED25519,
    CRYPTOGRAPHY_HAS_ED448,
    HAS_CRYPTOGRAPHY,
    OpenSSLObjectError,
    OpenSSLBadPassphraseError,
)

from .cryptography_crl import (
    REVOCATION_REASON_MAP,
    REVOCATION_REASON_MAP_INVERSE,
    cryptography_decode_revoked_certificate,
)

from .cryptography_support import (
    cryptography_get_extensions_from_cert,
    cryptography_get_extensions_from_csr,
    cryptography_name_to_oid,
    cryptography_oid_to_name,
    cryptography_get_name,
    cryptography_decode_name,
    cryptography_parse_key_usage_params,
    cryptography_get_basic_constraints,
    cryptography_key_needs_digest_for_signing,
    cryptography_compare_public_keys,
)

from .pem import (
    identify_private_key_format,
)

from .math import (
    binary_exp_mod,
    simple_gcd,
    quick_is_not_prime,
    count_bits,
)

from ._obj2txt import obj2txt as _obj2txt

from ._objects_data import OID_MAP as _OID_MAP

from ._objects import OID_LOOKUP as _OID_LOOKUP
from ._objects import NORMALIZE_NAMES as _NORMALIZE_NAMES
from ._objects import NORMALIZE_NAMES_SHORT as _NORMALIZE_NAMES_SHORT

from .pyopenssl_support import (
    pyopenssl_normalize_name,
    pyopenssl_get_extensions_from_cert,
    pyopenssl_get_extensions_from_csr,
)

from .support import (
    get_fingerprint_of_bytes,
    get_fingerprint,
    load_privatekey,
    load_certificate,
    load_certificate_request,
    parse_name_field,
    convert_relative_to_datetime,
    get_relative_time_option,
    select_message_digest,
    OpenSSLObject,
)

from ..io import (
    load_file_if_exists,
    write_file,
)
```

also i have virtual env managed by pipenv, ansible 5.4.0 is installed via pipenv, and same directories:
```
[zalent@*********** dev-machine]$ head /home/zalent/.local/share/virtualenvs/dev-machine-4LhYWgwz/lib/python3.9/site-packages/ansible_collections/community/crypto/CHANGELOG.rst 
==============================
Community Crypto Release Notes
==============================

.. contents:: Topics


v2.2.2
======

[zalent@*********** dev-machine]$ ls /home/zalent/.local/share/virtualenvs/dev-machine-4LhYWgwz/lib/python3.9/site-packages/ansible_collections/community/crypto/plugins/module_utils/crypto/
_asn1.py  basic.py  cryptography_crl.py  cryptography_support.py  math.py  module_backends  _obj2txt.py  _objects_data.py  _objects.py  openssh.py  pem.py  __pycache__  support.py
```
notice installation via pipenv lacks __init__.py and pyopenssl_support.py
and it works, however global installation for my user does not.

**Comment by felixfontein** [comment]
/home/zalent/.local/lib/python3.9/site-packages/ansible_collections/community/crypto/ seems to contain a mix of community.crypto 1.x.y and 2.2.2 files. You might need to reinstall ansible in your global installation for your user to clean that up.

**Comment by zalent** [comment]
indeed it was left overs from previous versions somehow. thanks!
